### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by xrmx** [martinogden/django-banner-rotator#10]
No idea how to reproduce, will try to debug, for now just filing for not forgetting :) 

 File "/venv/src/django-banner-rotator/banner_rotator/templatetags/banners.py", line 29, in render
    banner_obj.view()

AttributeError: 'NoneType' object has no attribute 'view'

**Comment by xrmx** [comment]
So this is a consequence of me removing the assert because of #9. When we don't get 1 as bias_list sum it may be possible that the random number would be higher that bias_list sum. I got number as 0.999851855491074804 and current as 0.9998. So no banner was picked.One fix i can think of is calling random.uniform(0, sum_of_bias) instead of random.random().

**Comment by martinogden** [comment]
So this should be fixed with the latest commit as we now normalize the `bias_list` in the pick method if it's not a valid probability distribution

**Comment by martinogden** [comment]
Fixed in `d5e3a264403fa6c536aaa6833eb6fd5c54d7cc5e`.
