### ISSUE TITLE
non english comments in managers.py

### ISSUE THREAD

**Issue by xrmx** [martinogden/django-banner-rotator#4]
Please translate BannerManager comments in english :)

**Comment by martinogden** [comment]
I've passed this on to the original contributor here: https://github.com/plazix/django-banner-rotator/issues/3

**Comment by martinogden** [comment]
Now removed

**Comment by xrmx** [comment]
Your revert wasn't clean and you have committed a conflict in models.py . Also i'm not so sure that you really wanted to revert the commit.
