### ISSUE TITLE
issues with south migrations

### ISSUE THREAD

**Issue by xrmx** [martinogden/django-banner-rotator#5]
django-extensions is needed if you use south because of django_extensions.db.fields.AutoSlugField in migrations. Could you please add a note about this in README please? Alternatively could you think on a better way to handle the issue?

**Comment by xrmx** [comment]
Oh well migration 0007 fails with sqlite:

`
south.exceptions.FailedDryRun:  ! Error found during dry run of '0007_places_new_params'! Aborting.
  File "app/banner_rotator/migrations/0007_places_new_params.py", line 25, in forwards
    db.add_column('banner_rotator_banner', 'place', self.gf('django.db.models.fields.related.ForeignKey')(default=None, related_name='banners', to=orm['banner_rotator.Place']), keep_default=False)
  File "venv/lib/python2.6/site-packages/south/db/sqlite3.py", line 25, in add_column
    raise ValueError("You cannot add a null=False column without a default value.")
ValueError: You cannot add a null=False column without a default value.
`

**Comment by xrmx** [comment]
I've started from scratch in my fork but don't think you want that:
https://github.com/xrmx/django-banner-rotator/commit/a7001d8272ed5fda45e84efe2f90308e39018f09

**Comment by dpolyakov** [comment]
i have same bug :(

**Comment by martinogden** [comment]
Added default value and fixed in `3bfc7acc821c993c27241c62bcf2326aa839aecf`.
